# Generated by Django 4.2 on 2023-05-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_convo_user_email_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpProvider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restapp.user')),
                ('fonction', models.CharField(max_length=20)),
            ],
            bases=('restapp.user',),
        ),
        migrations.RenameField(
            model_name='message',
            old_name='convo',
            new_name='convo_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='intent',
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='convo',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='speaker', to='restapp.user'),
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(default='', max_length=30)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.message')),
            ],
        ),
        migrations.CreateModel(
            name='entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('intent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.intent')),
            ],
        ),
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('convo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.convo')),
                ('help_provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='help_provider', to='restapp.helpprovider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='restapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='convo',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to='restapp.helpprovider'),
            preserve_default=False,
        ),
    ]
