# Generated by Django 4.2 on 2023-05-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_helpprovider_rename_convo_message_convo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connexion',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='convo',
            name='speaker',
        ),
        migrations.AlterField(
            model_name='convo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='restapp.user'),
        ),
    ]
