# Generated by Django 4.2 on 2023-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_remove_connexion_user_id_remove_convo_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_is_user',
            field=models.BooleanField(default=True),
        ),
    ]
