# Generated by Django 4.2 on 2023-05-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('intent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(verbose_name='data')),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='intent',
            name='message_id',
        ),
        migrations.DeleteModel(
            name='entity',
        ),
        migrations.DeleteModel(
            name='Intent',
        ),
    ]
