# Generated by Django 4.2 on 2023-06-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
