# Generated by Django 4.2 on 2023-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedObjectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(verbose_name='state')),
            ],
        ),
    ]
