# Generated by Django 4.2 on 2023-07-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restapp', '0016_managedobject_technology_delete_managedobjectstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LOCKED', 'LOCKED')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='DtSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_Time', models.DateTimeField()),
                ('dtTeam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restapp.managedobject')),
                ('technicien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
