# Generated by Django 4.2 on 2023-07-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0017_alter_technology_state_dtsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='id',
        ),
        migrations.AddField(
            model_name='technology',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
