# Generated by Django 4.2 on 2023-07-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0018_remove_technology_id_technology_auto_increment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='auto_increment_id',
            new_name='id',
        ),
    ]
