# Generated by Django 4.2 on 2023-07-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0019_rename_auto_increment_id_technology_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='id',
            new_name='auto_increment_id',
        ),
    ]
