# Generated by Django 4.2 on 2023-07-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0021_delete_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('3G', '3G'), ('4G', '4G'), ('2G', '2G')], max_length=2)),
                ('state', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('LOCKED', 'LOCKED')], max_length=6, null=True)),
                ('managedObject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='managedObject', to='restapp.managedobject')),
            ],
        ),
    ]
